// app/javascript/hello_react/app.jsx
import React from 'react'
import RowGenerator from './rowgenerator'
import axios from 'axios'

class App extends React.Component {
  state = {
    messages: {testkey: 'testvalue'}
  }


  componentDidMount() {
    axios.get('https://api.coindesk.com/v1/bpi/currentprice.json')
      .then(res => {
        this.setState({isLoaded: true, messages: res.data.bpi});
      })
  }


  render () {
      return (
          <div className="container">
            <h1>Bitcoin Price</h1>
            <RowGenerator messages={this.state.messages}/>
          </div>
        )
  }
}

export default App

// app/javascript/hello_vue/app.vue
<template>
    <div id="app" class="container">

      <h1>Bitcoin Price</h1>
      
      <table class="table table-striped">
        <tbody>
          <tr v-for="message in messages">
            <td>{{ message.code }} </td>
            <td>{{ message.rate }}</td>
            <td>{{ message.description }}</td>
          </tr>
        </tbody>
      </table>
    </div>

</template>

<script>
import axios from 'axios'

export default {
  data: function () {
    return {
      messages: "Hello Vue!"
    }
  },
  mounted() {
    axios.get('https://api.coindesk.com/v1/bpi/currentprice.json')
      .then(res => {
        this.messages = res.data.bpi;
      })
  }
}
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
