// app/javascript/hello_vue/app.vue
<template>
    <div id="app">

    <h1>Bitcoin Price</h1>
    
    <table class="table table-striped">
      <tbody>
        <tr v-for="message in messages">
          <td>{{ message.code }} </td>
          <td>{{ message.rate }}</td>
          <td>{{ message.description }}</td>
        </tr>
      </tbody>
    </table>
    </div>

</template>

<script>
import axios from 'axios'

export default {
  data: function () {
    return {
      messages: "Hello Vue!"
    }
  },
  mounted() {
    axios.get('https://api.coindesk.com/v1/bpi/currentprice.json')
      .then(res => {
        this.messages = res.data.bpi;
      })
  }
}
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>

// app/javascript/hello_angular/app/app.component.ts
import { Component } from '@angular/core';

import { AppService } from './app.service';


@Component({
  selector: 'hello-angular',
  template: `<table class='table table-striped'>
              <tbody>              
                <tr *ngFor="let message of messages | keyvalue">            
                  <td>{{message.value.code}}</td>
                  <td>{{message.value.rate}}</td>
                  <td>{{message.value.description}}</td>
                </tr>
              </tbody>
            </table>`,
  providers: [ AppService ],

})
export class AppComponent {
  messages = ['Angular!', '2', '3'];

  constructor(private appService: AppService) {}

  getData() {
      this.appService.getData()
        .subscribe(
            data => {
                      this.messages = data.bpi;
                      console.log(this.messages);
                     }
        ); 
  }


  ngOnInit(){
    this.getData();
  }
}
